version: '3.8'

services:
  gateway:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - uploader
        - downloader
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin; do echo '...waiting minio...'; sleep 1; done;
      /usr/bin/mc mb myminio/docs-storage --ignore-existing;
      exit 0;
      "

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  uploader:
    build:
      context: .
      dockerfile: deploy/docker/uploader.Dockerfile
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ID=minioadmin
      - MINIO_SECRET=minioadmin
      - MINIO_BUCKET=docs-storage
      - REDIS_ADDR=redis:6379
      - HTTP_PORT=8080
    depends_on: [minio, redis, rabbitmq]

  downloader:
    build:
      context: .
      dockerfile: deploy/docker/downloader.Dockerfile
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ID=minioadmin
      - MINIO_SECRET=minioadmin
      - MINIO_BUCKET=docs-storage
      - REDIS_ADDR=redis:6379
      - HTTP_PORT=8081
    depends_on: [minio, redis]
  signer:
    build:
      context: .
      dockerfile: deploy/docker/signer.Dockerfile
    environment:
      - DB_DSN=postgres://user:password@postgres:5432/signer_db
      - RABBIT_URL=amqp://user:password@rabbitmq:5672/
      - HTTP_PORT=8082
    ports:
      - "8082:8082" 
    depends_on: [postgres, rabbitmq]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: signer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  minio_data:
  postgres_data: