apiVersion: v1
kind: Secret
metadata:
  name: signer-secrets
  namespace: default
type: Opaque
stringData:
  MINIO_ID: "minioadmin"
  MINIO_SECRET: "minioadmin"

  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "signer_db"

  DB_DSN: "postgres://user:password@postgres:5432/signer_db"
  RABBIT_URL: "amqp://user:password@rabbitmq:5672/"

  MASTER_KEY_HEX: "__PUT_64_HEX_HERE__"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: signer-config
  namespace: default
data:
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_BUCKET: "docs-storage"
  MINIO_REGION: "us-east-1"

  REDIS_ADDR: "redis:6379"

  PDFSIGN_URL: "http://pdfsigner:8090/sign"
