apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signer-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: signer.local
    http:
      paths:
      - path: /download
        pathType: Prefix
        backend: 
          service: 
            name: downloader-svc
            port: 
              number: 80
      - path: /view
        pathType: Prefix
        backend: 
          service: 
            name: downloader-svc
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend: 
          service: 
            name: uploader-svc
            port: 
              number: 80
      - path: /api/
        pathType: Prefix
        backend: 
          service: 
            name: signer-svc
            port: 
              number: 80