name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Registry Image Name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
        
      - name: Build and push Uploader
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/docker/uploader.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/uploader:latest
      - name: Build and push Downloader
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/docker/downloader.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/downloader:latest
      - name: Build and push Signer
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/docker/signer.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/signer:latest
      - name: Build and push PdfSigner
        uses: docker/build-push-action@v4
        with:
          context: ./pdfsigner
          file: ./pdfsigner/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/pdfsigner:latest
